### ISSUE TITLE
Configuring HTTP proxy as described in our docs no longer works in Node@18 and @20

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-sdk-javascript#1646]
# Bug Report

## Description

Since v18, Node ships with a native fetch client. This client requires a different way to specify an HTTP proxy than what we've been supporting in our SDKs so far.

To specify an HTTP proxy for Node's fetch, you need to use the following code (tested on Node v18.19 and v20.11):

```ts
import { ProxyAgent } from 'undici';
import { Client } from '@microsoft/microsoft-graph-client';

const dispatcher = new ProxyAgent(process.env.https_proxy);
const fetchOptions = {
  dispatcher
};

Client.initWithMiddleware({
  middleware,
  fetchOptions
});
```

What's noteworthy:
- we specify HTTP proxy using dispatcher instead of agent (agent is ignored on requests, which makes it hard to debug)
- the ProxyAgent dispatcher comes from undici which seems to be maintained by Node folks. The ProxyAgent is incompatible with other agents that we used to use in the past.

We should update our FetchOptions interface to support specifying dispatcher.

**Console Errors:** no

## Steps to Reproduce

1. Configure an http proxy as specified in our docs

**Expected behavior:** web requests intercepted by the specified proxy

**Actual behavior:** web requests passed through without being intercepted

## Usage Information

SDK Version - 3.06

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v18.19 and v20.11

**Comment by sebastienlevert** [comment]
Thanks for the report! At this point, core enhancements won't be added to this library by the team. A PR would be reviewed though.

Also, could this be fixed with just docs? Very suboptimal, but could be an option.

Thoughts?

**Comment by waldekmastykarz** [comment]
As far as I can tell, the only thing we need to change in the code is the type that defines fetch options, so that it includes the new dispatcher property. Other than that, we need to update docs and explain how to use it. The code itself works just fine.

**Comment by feedmypixel** [comment]
Came across this problem on Node `v20.11.1` we were using something similar to  - https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=typescript#configuring-the-http-proxy-for-the-client:

```
// Create a client with the proxy
const graphClient = Client.initWithMiddleware({
  authProvider: authProvider,
  fetchOptions: {
    agent: proxyAgent,
  },
});
```

This was giving us a `fetch failed` error.

After reverse engineering things and reading through various posts we arrived at https://github.com/nodejs/undici/issues/1350#issuecomment-1137916129

As we are `Js` and not `Ts`, we have ended up with:

```
const graphClient = Client.initWithMiddleware({
  debugLogging: true,
  authProvider,
  fetchOptions: {
    dispatcher: new ProxyAgent({
      uri: proxyUrl,
      keepAliveTimeout: 10,
      keepAliveMaxTimeout: 10
    })
  }
})
```

Thought this might help someone in the future.

**Comment by jack-feddersen** [comment]
Hi there,
I also just came across this and was referencing the docs, wondering why my proxy was never being used. The difficult thing is that when you do it like the docs say, it fails silently.
Although the types are there in the sdk now, it was sometimes showing type errors still, and it only links you to the official `fetch` documentation. Updating the documentation online would be a great idea, I think. Maybe I could do it if it's wanted.
Many thanks to @feedmypixel for your answer, as it did help me!

**Comment by am35-00** [comment]
## **UPDATE**:
Created a ticket for this #1990 
___

I'm having a similar issue. I'm running an express app using Node v18.19.1. My endpoint does the following:

1. Saves a document to a sharepoint folder
2. Performs the download/convert to pdf
3. Saves the downloaded pdf to a Mongo db.
4. Deletes the original file

Steps 1, 2, and 4 use the `@microsoft/microsoft-graph-client@3.0.7` package. This all works locally. However, when I deploy it to my Azure App Services (running windows), it breaks at step 2 with the following error:

```
TypeError: fetch failedat node:internal/deps/undici/undici:12625:11
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The conversion download method:
``` javascript
const conversionDownloadToPdf = async (fileItemId) => {
    try {
        console.log(chalk.blue(`Attempting to downloaded file (${fileItemId})...`));

        const response = await client.api(`drives/${process.env.DRIVE_ID}/items/${fileItemId}/content?format=pdf`)
            .responseType(ResponseType.RAW) // ensure raw stream
            .get();

        const stream = await apiRequest.responseType(ResponseType.RAW).get(); // BREAKS HERE

        console.log(chalk.blue(`Stream downloaded. Streaming to buffer...`));
      
        return await toBuffer(stream);
    } catch (error) {
        console.error(chalk.red(`Full error details:`));
        console.error(chalk.red(`Message: ${error.message}`));
        console.error(chalk.red(`Status Code: ${error.statusCode}`));
        console.error(chalk.red(`Code: ${error.code}`));
        console.error(chalk.red(`Stack: ${error.stack}`));
        
        // Log the cause if available (undici errors have this)
        if (error.cause)
            console.error(chalk.red(`Cause: ${JSON.stringify(error.cause, null, 2)}`));

        throw error;
    }
}
```
Do I need to use that ProxyAgent? Do you have official docs on a workaround?
